spring:
  config:
    import: optional:file:.env[.properties]
transaq:
  login: ${TRANSAQ_LOGIN}
  password: ${TRANSAQ_PASSWORD}
  newPassword: ${TRANSAQ_NEW_PASSWORD}
  host: ${TRANSAQ_HOST}
  port: ${TRANSAQ_PORT}